application: yourapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: yourapp/handlers/home.py

- url: /about/.*
  script: yourapp/handlers/about.py

- url: /projects/.*
  script: yourapp/handlers/projects.py

